k3s_cluster:
  children:
    master:
      hosts:
        10.10.0.11:
        10.10.0.12:
        10.10.0.13:
    node:
      hosts:
        10.10.0.14:

  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    ansible_user: k3s-user
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_cloudinit_k3s
    ansible_python_interpreter: /usr/bin/python3
